## *Tranches* sur les tableaux

In [1]:
from numpy import *

In [2]:
a = array([2.0, 4, 6, 8, 10, 12, 14, 16, 18])
print(a)
print(a[3])

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
8.0


In [3]:
print(a[3:7])
print(a[3:])
print(a[:7])

[ 8. 10. 12. 14.]
[ 8. 10. 12. 14. 16. 18.]
[ 2.  4.  6.  8. 10. 12. 14.]


In [4]:
b = a[3:7]
print(len(b))
print(b[3])
print(b)

4
14.0
[ 8. 10. 12. 14.]


NB: en Python, la plupart des éléments qui supportent la notation `[i]` supportent également la notation `[i:j]` (chaînes, listes, tuples...).

### *Tranches* et mutabilité

Ce qui suit, en revanche, n'est valable **que** pour les tableaux.

Une modification sur une tranche d'un tableau se répercute sur le tableau global.

In [5]:
b[0] = 42
print(a)

[ 2.  4.  6. 42. 10. 12. 14. 16. 18.]


## Fonctions récursives sur les tableaux

In [6]:
def somme(a: [float]) -> float:
    """
    :pré-cond: ø
    :post-cond: retourne la somme des éléments de a
    """
    if len(a) == 0:
        s = 0
    else:
        s = a[0] + somme(a[1:])
    return s

In [7]:
# récursion en retirant la première case
def indice_min(a: [float]) -> int:
    """
    :pré-cond: len(a)>0
    :post-cond: retourne imin tq. a[imin]≤a[i] pour tout i dans [0;len(a)[
    """
    if len(a) == 1:
        imin = 0
    else:
        imin = indice_min(a[1:])+1
        if a[0] < a[imin]:
            imin = 0
    return imin

# récursion en retirant la dernière case
def indice_min(a: [float]) -> int:
    """
    :pré-cond: len(a)>0
    :post-cond: retourne imin tq. a[imin]≤a[i] pour tout i dans [0;len(a)[
    """
    if len(a) == 1:
        imin = 0
    else:
        maxi = len(a)-1
        imin = indice_min(a[:maxi])
        if a[maxi] < a[imin]:
            imin = maxi
    return imin

In [8]:
def inverse(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: ø
    :post-cond: pour tout i dans [0;len(a)[ aₑ[i]=aₛ[len(a)-1-i]
    """
    if len(a)<2:
        pass
    else:
        tmp = a[0]
        a[0] = a[len(a)-1]
        a[len(a)-1] = tmp
        inverse(a[1:len(a)-1])

## Tri par sélection

In [9]:
# version récursive

def tri_sélection(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: ø
    :post-cond: a_s est la version triée par ordre croissant de a_e
    """
    if len(a)<2:
        pass
    else:
        imax = indice_max(a)
        a[imax],a[len(a)-1] = a[len(a)-1],a[imax]
        tri_sélection(a[:len(a)-1])
        
# version itérative

def tri_sélection(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: ø
    :post-cond: a_s est la version triée par ordre croissant de a_e
    """
    i = len(a) # nombre de case restant à trier
    while i>1:
        imax = indice_max(a[:i])
        a[imax],a[i-1] = a[i-1],a[imax]
        i = i-1
        
def indice_max(a: [float]) -> int:
    """
    :pré-cond: len(a)>0
    :post-cond: retourne imax tq. a[imax]≥a[i] pour tout i
    """
    imax = 0
    for i in range(1, len(a)):
        if a[i] > a[imax]:
            imax = i
    return imax
    
a = array([2,9,3,8,4,7,5,6])
tri_sélection(a)
print(a)

[2 3 4 5 6 7 8 9]


La complexité du tri par sélection est en $O(n^2)$. En effet, à chaque étape de la boucle (lignes 25-28), l'appel à la fonction `indice_max` prend un temps proportionnel à la taille du tableau.