In [1]:
from numpy import *

def f(a: [float]) -> float:
    a[0] = a[0]+1
    return a[0]

mon_tableau = array([2.0, 4.0, 6.0])
print( f(mon_tableau) )
print(mon_tableau)

3.0
[3. 4. 6.]


In [2]:
# lorsqu'un tableau est un paramètre d'entrée d'une fonction
# la fonction ne DOIT PAS le modifier

# on introduit un nouveau type de paramètre :
# les paramètres d'entrée/sortie (e/s),
# que la fonction est autorisée à modifier

def inverse_en_place(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: ø
    :post-cond: pour tout i dans [0,len(a)[
                a_s[i] = a_e[len(a)-1-i]
    """
    i = 0
    while i < len(a)//2:
        tmp = a[i]
        a[i] = a[len(a)-1-i]
        a[len(a)-1-i] = tmp
        i = i+1
    
mon_tableau = array([2.0, 4.0, 6.0, 8.0, 10.0])
inverse_en_place(mon_tableau)
print(mon_tableau)

[10.  8.  6.  4.  2.]


In [3]:
def normalise_en_place(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: len(a)>0
    :post-cond: soient min et max les valeurs extrèmes du tableau,
        remplace chaque valeur a[i] par (a[i]-min)/(max-min).
        NB: si le tableau contient des valeurs toutes identiques,
        on les remplace toutes par 0.
    """
    min = max = a[0]
    i = 1
    while i<len(a):
        if a[i] < min:
            min = a[i]
        else:
            if a[i] > max:
                max = a[i]
        i = i+1
    if max!=min:
        écart = max-min
        i = 0
        while i<len(a):
            a[i] = (a[i]-min)/écart
            i = i+1
    else:
        i = 0
        while i<len(a):
            a[i] = 0
            i = i+1

# version alternative avec des boucles 'for'

def normalise_en_place(a: [float]):
    """
    :e/s a: [float]
    :pré-cond: len(a)>0
    :post-cond: soient min et max les valeurs extrèmes du tableau,
        remplace chaque valeur a[i] par (a[i]-min)/(max-min).
        NB: si le tableau contient des valeurs toutes identiques,
        on les remplace toutes par 0.
    """
    min = max = a[0]
    for e in a:
        if e < min:
            min = e
        else:
            if e > max:
                max = e
    if max!=min:
        écart = max-min
        for i in range(len(a)):
            a[i] = (a[i]-min)/écart
    else:
        for i in range(len(a)):
            a[i] = 0

mon_tableau = array([5.0, 9.0, 7.0, 10.0, 7.0, 6.0])
normalise_en_place(mon_tableau)
print(mon_tableau)

[0.  0.8 0.4 1.  0.4 0.2]


In [4]:
# factorielle, version itérative (boucle while)

def fact(n:int) -> int:
    """
    :pré-cond: n>0
    :post-cond: retourne n! = 1x2x3x...x(n-1)xn
    """
    f = 1
    i = 2
    while i <= n:
        f = f*i
        i = i+1
    return f

# factorielle, version récursive

def fact(n: int) -> int:
    """
    :pré-cond: n>0
    :post-cond: retourne n! = 1x2x3x...x(n-1)xn
    """
    if n == 1:
        f = 1
    else:
        f = n*fact(n-1)
    return f

fact(6)

720