In [1]:
from numpy import *

In [2]:
def inverse(a: [float]) -> [float]:
    """
    :pré-cond: ø
    :post-cond: retourne un tableau inv tel que
        len(inv) = len(a)
        pour tout i inv[i] == a[len(a)-1-i]
    """
    inv = empty(len(a), float)
    i = 0
    j = len(inv)-1
    while i < len(a):
        inv[j] = a[i]
        i = i+1
        j = j-1
    return inv
        
print( inverse(array([2,4,6,8,10.0])))

[10.  8.  6.  4.  2.]


In [3]:
def premiers(n: int) -> [int]:
    """
    :pré-cond: n>0
    :post-cond: retourne un tableau contenant
        les n premiers nombres premiers
    """
    prem = empty(n, int)
    trouvés = 0
    candidat = 2
    while trouvés < n:
        premier = True
        i = 0
        while premier and i<trouvés and prem[i]*prem[i]<=candidat:
            if candidat%prem[i]==0:
                premier = False
            i = i+1
        if premier:
            prem[trouvés] = candidat
            trouvés = trouvés+1      
        candidat = candidat+1
    return prem

print( premiers(100) )

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
 467 479 487 491 499 503 509 521 523 541]


In [4]:
def décompresse(comp: [int]) -> [int]:
    """
    :pré-cond: len(comp) est paire
        pour tout i impair comp[i] > 0
    :post-cond: retourne le tableau représenté par 'comp'
        ou chaque couple de valeur de comp représente
        une valeur suivie de son nombre d'occurences
        ex: [-2 4 3 2 0 5 1 1] -> [-2 -2 -2 -2 3 3 0 0 0 0 0 1]
    """
    len_totale = 0
    i = 1
    while i<len(comp):
        len_totale = len_totale + comp[i]
        i = i+2
    data = empty(len_totale, int)
    
    ic = 0 # indice dans comp
    id = 0 # indice dans data
    while ic<len(comp):
        val = comp[ic]
        nb_val = comp[ic+1]
        while nb_val > 0:
            data[id] = val
            id = id+1
            nb_val = nb_val-1        
        ic = ic+2
    return data

print( décompresse(array([-2, 4, 3, 2, 0, 5, 1, 1])) )

[-2 -2 -2 -2  3  3  0  0  0  0  0  1]


## Tableaux et mutabilité

In [5]:
a = 42

def f(n: int) -> int:
    n = -n
    return n

print( f(a) )
print( a    )

-42
42


In [6]:
a = 42
b = a
b = b+1
print(  b  )
print(  a  )

43
42


In [7]:
a = array([42,3,42])
b = a
b[0] = b[0]+1
print(  b  )
print(  a  )

[43  3 42]
[43  3 42]


In [8]:
a = array([42])
b = a
b = array([43])
print(  b  )
print(  a  )

[43]
[42]


In [9]:
a = array([42])

def f(b: [int]) -> int:
    b[0] = -b[0]
    return b[0]

print(  f(a)  )
print(  a     )

-42
[-42]
